# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
development:
  adapter: postgresql
  database: db/creative_tech_kids_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/creative_tech_kids_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/creative_tech_kids_production
  pool: 5
  timeout: 5000
